Vagrant.configure(2) do |config|
  config.vm.guest = :windows
  config.vm.communicator            = "ssh"
  config.ssh.username               = "vagrant"
  config.ssh.password               = "vagrant"
  config.ssh.insert_key             = false
  config.vm.boot_timeout            = 1000
  config.vm.network :forwarded_port, guest: 3389, host: 3389, id: 'rdp', auto_correct: true
  config.vm.network :forwarded_port, guest: 5986, host: 5986, id: "winrm-ssl", auto_correct:true
  config.vm.network :forwarded_port, guest: 5985, host: 5985, id: "winrm", auto_correct:true
  config.vm.network :forwarded_port, guest: 22, host: 22, id: "ssh", auto_correct:true
  config.vm.provider :libvirt do |guest|
    guest.cpus                      = 2
    guest.memory                    = 4096 
    guest.disk_bus                  = "virtio"
    guest.nic_model_type            = "virtio"
    guest.nic_model_type            = "virtio"
    guest.graphics_type             = "spice"
    guest.graphics_port             = -1
    guest.graphics_ip               = "0.0.0.0"
    guest.graphics_autoport         = "yes"
    guest.video_type                = "virtio"
    guest.channel :type  => 'spicevmc', :target_name => 'com.redhat.spice.0',     :target_type => 'virtio'
    guest.channel :type  => 'unix',     :target_name => 'org.qemu.guest_agent.0', :target_type => 'virtio'
  end
  
  config.vm.synced_folder ".", "/vagrant", type: "nfs", disabled: true
  config.vm.synced_folder ".", "/vagrant", disabled: true
end
