---
- name: "{{ task_name }}"
  ansible.builtin.include_tasks: home.yml
  when: parrotos_edition == 'home'

- name: "{{ task_name }}"
  ansible.builtin.include_tasks: security.yml
  when: parrotos_edition == "security"
