---
- name: "{{ updates_task_name }}"
  ansible.builtin.include_tasks: linux.yml
  when: ansible_os_family in ['Debian', 'RedHat', 'Suse']

- name: "{{ updates_task_name }}"
  ansible.builtin.include_tasks: windows.yml
  when: ansible_os_family == "Windows"
