---
# Windows

- name: Check if Red Hat certificate is not already installed
  ansible.windows.win_powershell:
    script: |
      Get-ChildItem -Path Cert:\LocalMachine\TrustedPublisher | Select-String -Pattern "Red Hat"
  changed_when: false
  register: cert_check

- name: Ensure Qemu Guest Agent is installed on the system
  block:
    - name: Install Qemu Guest Agent v0.1.248
      ansible.windows.win_package:
        path: "{{ virtio_win_iso_path }}\\guest-agent\\qemu-ga-x86_64.msi"
        creates_path: "{{ ansible_env['ProgramFiles'] }}\\qemu-ga"
        arguments:
          - /install
          - /passive
          - /norestart

- name: Install RH certificate
  # when: cert_check.output[0] is not search("Red Hat")
  when: not cert_check.output
  block:
    - name: Export Cert from balloon
      ansible.windows.win_powershell:
        script: |
          $cert = (Get-AuthenticodeSignature "{{ virtio_win_iso_path }}\Balloon\{{ virtio_driver_directory }}\amd64\blnsvr.exe").SignerCertificate
          [System.IO.File]::WriteAllBytes("{{ ansible_env.TEMP }}\rh.cer", $cert.Export([System.Security.Cryptography.X509Certificates.X509ContentType]::Cert))

    - name: Install RH certificate (Balloon) to TrustedPublisher certificate store
      ansible.windows.win_command:
        cmd: certutil.exe -f -addstore "TrustedPublisher" {{ ansible_env.TEMP }}\rh.cer

  rescue:
    - name: Print when errors
      ansible.builtin.debug:
        msg: "I caught an error..."

- name: Ensure Spice Tools are installed on the system
  when: cert_check.output[0] is search("Red Hat")
  block:
    - name: Download Spice Tools to {{ ansible_env.TEMP }}
      ansible.windows.win_get_url:
        url: "{{ spice_tools_uri }}"
        force: false
        dest: "{{ ansible_env.TEMP }}\\spice-guest-tools-latest.exe"

    - name: Install Spice Tools
      ansible.windows.win_package:
        path: "{{ ansible_env.TEMP }}\\spice-guest-tools-latest.exe"
        creates_path: "{{ ansible_env['ProgramFiles(x86)'] }}\\SPICE Guest Tools"
        arguments:
          - /S
