---
- name: Play to install Qemu Guest agent and Spice Tools.
  debugger: never
  gather_facts: true
  hosts: all
  roles:
    - role: qemu-agent
      vars:
        virtio_driver_directory: 2k22
        virtio_win_iso_path: "F:\\"
        spice_tools_uri: "https://www.spice-space.org/download/windows/spice-guest-tools/spice-guest-tools-latest.exe"
    # - base
    # - configure
